[package]
name = "local-server-host"
version = "0.1.0"
edition = "2024"

# Not a member of the sdk-core workspace.
[workspace]

[features]
default = ["tls-ring"]
tls-ring = ["temporalio-client/tls-ring"]

[dependencies]
anyhow = "1"
futures-util = "0.3"
prost = "0.14"
temporalio-client = { path = "../crates/client", default-features = false }
tokio = { version = "1.47", features = ["sync", "time", "macros"] }
tonic = { version = "0.14.6", default-features = false }
prost-types = { version = "0.7", package = "prost-wkt-types" }
wasmtime = { version = "48", default-features = false, features = ["runtime", "std", "anyhow"] }
wasmtime-wasi = "48"
temporalio-protos = { path = "../crates/protos" }
libc = "0.2"
